web_flask/onlineqa/qa_flask/accounts/forms.py
import hashlib

from flask import request
from flask_login import login_user
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, ValidationError
from wtforms.validators import DataRequired, Length, EqualTo

from models import User, db, UserProfile, UserLoginHistory
from utils import constants
from utils.validators import phone_required


class RegisterForm(FlaskForm):
    """ 用户注册 """
    username = StringField(label='用户名', render_kw={
        'class': 'form-control input-lg',
        'placeholder': '请输入用户名'
    }, validators=[DataRequired('请输入用户名'), phone_required])
    nickname = StringField(label='用户昵称', render_kw={
        'class': 'form-control input-lg',
        'placeholder': '请输入用户昵称'
    }, validators=[DataRequired('请输入用户昵称'),
                   Length(min=2, max=20, message='昵称长度在2-20之间')])
    password = PasswordField(label='密码', render_kw={
        'class': 'form-control input-lg',
        'placeholder': '请输入密码'
    }, validators=[DataRequired('请输入密码')])
    confirm_password = PasswordField(label='确认密码', render_kw={
        'class': 'form-control input-lg',
        'placeholder': '请输入确认密码'
    }, validators=[DataRequired('请输入确认密码'),
                   EqualTo('password', message='两次密码输入不一致')])

    def validate_username(self, field):
        """ 检测用户名是否已经存在 """
        user = User.query.filter_by(username=field.data).first()
        if user:
            raise ValidationError('该用户名已经存在')
        return field

    def register(self):
        """ 自定义的用户注册函数 """
        # 1. 获取表单信息
        username = self.username.data
        password = self.password.data
        nickname = self.nickname.data
        # 2. 添加到db.session
        try:
            # 将密码加密存储
            password = hashlib.sha256(password.encode()).hexdigest()
            user_obj = User(username=username, password=password, nickname=nickname)
            db.session.add(user_obj)
            profile = UserProfile(username=username, user=user_obj)
            db.session.add(profile)
            db.session.commit()
            return user_obj
        except Exception as e:
            print(e)
        return None


class LoginForm(FlaskForm):
    """ 用户登录 """
    username = StringField(label='用户名', render_kw={
        'class': 'form-control input-lg',
        'placeholder': '请输入用户名'
    }, validators=[DataRequired('请输入用户名'), phone_required])
    password = PasswordField(label='密码', render_kw={
        'class': 'form-control input-lg',
        'placeholder': '请输入密码'
    }, validators=[DataRequired('请输入密码')])

    def validate(self):
        result = super().validate()
        username = self.username.data
        password = self.password.data
        if result:
            # TODO 验证加密后的密码是否正确
            user = User.query.filter_by(username=username, password=password).first()
            if user is None:
                result = False
                self.username.errors = ['用户名或者是密码错误']
            elif user.status == constants.UserStatus.USER_IN_ACTIVE.value:
                result = False
                self.username.errors = ['用户已被禁用']
        return result

    def do_login(self):
        """ 执行登录逻辑代码 """
        username = self.username.data
        password = self.password.data
        try:
            # 1. 查找对应的用户
            # TODO 验证加密后的密码是否正确
            user = User.query.filter_by(username=username, password=password).first()
            # 2. 登录用户
            # session['user_id'] = user.id
            login_user(user)
            # 3. 记录日志
            ip = request.remote_addr
            ua = request.headers.get('user-agent', None)
            obj = UserLoginHistory(username=username, ip=ip, ua=ua, user=user)
            db.session.add(obj)
            db.session.commit()
            return user
        except Exception as e:
            print(e)
        return None

web_flask/onlineqa/qa_flask/accounts/views.py
import hashlib

from flask import Blueprint, render_template, flash, redirect, url_for, session, request
from flask_login import login_user, logout_user

from accounts.forms import RegisterForm, LoginForm
from models import User, db, UserProfile, UserLoginHistory

accounts = Blueprint('accounts', __name__,
                     template_folder='templates',
                     static_folder='../assets')


@accounts.route('/login', methods=['GET', 'POST'])
def login():
    """ 登录页面 """
    form = LoginForm()
    next_url = request.values.get('next', url_for('qa.index'))
    if form.validate_on_submit():
        user = form.do_login()
        if user:
            # 4. 跳转到首页
            flash('{}, 欢迎回来'.format(user.nickname), 'success')
            return redirect(next_url)
        else:
            flash('登录失败，请稍后重试', 'danger')
    # else:
    #     print(form.errors)
    return render_template('login.html', form=form, next_url=next_url)


@accounts.route('/logout')
def logout():
    """ 退出登录 """
    # 自定义登录的逻辑代码
    # session['user_id'] = ''
    # g.current_user = None
    logout_user()
    flash('欢迎下次再来', 'success')
    return redirect(url_for('accounts.login'))


@accounts.route('/register', methods=['GET', 'POST'])
def register():
    """ 注册 """
    form = RegisterForm()
    if form.validate_on_submit():
        user_obj = form.register()
        if user_obj:
            # 跳转到登录的页面
            flash('注册成功，请登录', 'success')
            return redirect(url_for('accounts.login'))
        else:
            flash('注册失败，请稍后再试', 'danger')
    return render_template('register.html', form=form)


@accounts.route('/mine')
def mine():
    """ 个人中心 """
    return render_template('mine.html')


web_flask/onlineqa/qa_flask/accounts/templates/login.html
{% extends 'base.html' %}
{% from 'macro/form_errors.html' import form_field_errors %}
{% block title %}{{ super() }}-登录{% endblock %}
{% block header %}
  <link rel="stylesheet" href="./assets/style/login.css">
  <link rel="stylesheet" href="//at.alicdn.com/t/font_1658093_nokjvsp8hws.css">
{% endblock %}
{% block layout %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        {# 展示flash消息 #}
        {% include 'components/flash_messages.html' %}
        <!-- // 消息通知区域 -->
        <div class="login-header">
          <h2 class="title text-center">在线问答系统登录</h2>
          <div class="slogan text-center">有问题 上问答</div>
        </div>
        <!-- 表单登录 -->
        <!-- 表单登录 -->
        <form class="login-form box-wrap" method="POST"
              action="{{ url_for('accounts.login') }}">
          <input type="hidden" name="next" value="{{ next_url|d('') }}">
          {{ form.csrf_token }}
          <div class="form-group">
            <label for="id-user-name">用户名</label>
            {{ form.username }}
          </div>
          {{ form_field_errors(form.username.errors) }}
          <div class="form-group">
            <label for="id-password">密码</label>
            {{ form.password }}
          </div>
          {{ form_field_errors(form.password.errors) }}
          <div class="form-group">
            <button type="submit" class="btn btn-info btn-block btn-lg">登录</button>
          </div>
          <p class="desc">未注册手机验证后自动登录<br />
            注册即代表同意《用户使用协议》《隐私保护指引》</p>
          <p class="text-right">没有账号，<a href="register.html">点击注册</a></p>
        </form>
        <!-- //表单登录 -->
        <!-- 社交账号登录 -->
        <div class="login-social box-wrap">
          <span>社交账号登录</span>
          <div class="right">
            <span><i class="iconfont icon-wechat"></i>微信</span>
            <span><i class="iconfont icon-qq"></i>QQ</span>
            <span><i class="iconfont icon-weibo"></i>微博</span>
          </div>
        </div>
        <!-- //社交账号登录 -->
        <!-- 页脚 -->
        <div class="login-footer">
          <a href="">关于我们</a>
          <a href="">联系我们</a>
          <a href="">注册机构</a>
          <a href="">专栏</a>
          <br>
          <a href="">京ICP 备1000000012号</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

web_flask/onlineqa/qa_flask/accounts/templates/mine.html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
  <title>在线问答系统-个人中心</title>

  <!-- Bootstrap -->
  <link href="./assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
  <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
  <!--[if lt IE 9]>
      <script src="./assets/plugins/html5shiv.min.js"></script>
      <script src="./assets/plugins/respond.min.js"></script>
    <![endif]-->

  <link rel="stylesheet" href="./assets/style/common.css">
  <link rel="stylesheet" href="./assets/style/mine.css">
</head>

<body class="layout">
  <!-- 顶部导航 -->
  <div class="layout-header">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#id-index-banner"
            aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="./index.html">在线问答系统</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="id-index-banner">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">首页 <span class="sr-only">(current)</span></a></li>
            <li><a href="#">话题</a></li>
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="搜索话题">
            </div>
            <button type="submit" class="btn btn-default">搜索</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">提问</a></li>
            <li><a href="#">消息<span class="badge">4</span></a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                aria-expanded="false">个人中心 <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">我的主页</a></li>
                <li><a href="#">设置</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">退出</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>
  <!-- // 顶部导航 -->
  <!-- 顶部个人信息 -->
  <div class="layout-personal">
    <div class="container">
      <div class="main-top">
        <img src="./assets/home/qa/personal_top.jpg" alt="">
      </div>
      <div class="main-bottom">
        <div class="content-left">
          <img src="./assets/home/qa/personal_avatar.jpg" alt="">
        </div>
        <div class="content-right">
          <h3>NavCat</h3>
          <div class="desc">
            创业是一次孤独的旅行
          </div>
          <div class="info-row">
            <i class="glyphicon glyphicon-folder-close"></i> <span>计算软件</span>
          </div>
          <div class="info-row">
            <i class="glyphicon glyphicon-certificate"></i> <span>男</span>
          </div>
          <button class="btn btn-default btn-gray" type="button">编辑个人资料</button>
        </div>
      </div>
    </div>
  </div>
  <!-- // 顶部个人信息 -->
  <div class="container layout-main">
    <div class="row">
      <div class="col-md-9">
        <!-- 左侧内容区域 -->
        <div class="main-left">
          <ul class="nav nav-tabs">
            <li role="presentation"><a href="#">动态</a></li>
            <li role="presentation"><a href="#">回答</a></li>
            <li role="presentation" ><a href="#">收藏</a></li>
            <li role="presentation" class="active"><a href="#">关注</a></li>
            <li role="presentation"><a href="#">文章</a></li>
          </ul>
          <div class="title">我关注的问题</div>
          <!-- 我关注的问题列表 -->
          <ul class="flllow-qa-ls">
            <li>
              <a href="../../qa/templates/detail.html">疫情结束后会爆发消费狂潮吗？</a>
              <div class="stats">2020-3-1 · 15个回答 ·  20个关注</div>
            </li>
            <li>
              <a href="../../qa/templates/detail.html">钟南山说「我们也做了疫情预测模型，投稿到国外权威期刊被退了回来」，你怎么看？</a>
              <div class="stats">2020-3-1 · 15个回答 ·  20个关注</div>
            </li>
            <li>
              <a href="../../qa/templates/detail.html">疫情结束后会爆发消费狂潮吗？</a>
              <div class="stats">2020-3-1 · 15个回答 ·  20个关注</div>
            </li>
            <li>
              <a href="../../qa/templates/detail.html">钟南山说「我们也做了疫情预测模型，投稿到国外权威期刊被退了回来」，你怎么看？</a>
              <div class="stats">2020-3-1 · 15个回答 ·  20个关注</div>
            </li>
            <li>
              <a href="../../qa/templates/detail.html">疫情结束后会爆发消费狂潮吗？</a>
              <div class="stats">2020-3-1 · 15个回答 ·  20个关注</div>
            </li>
            <li>
              <a href="../../qa/templates/detail.html">钟南山说「我们也做了疫情预测模型，投稿到国外权威期刊被退了回来」，你怎么看？</a>
              <div class="stats">2020-3-1 · 15个回答 ·  20个关注</div>
            </li>
          </ul>
          <!-- // 我关注的问题列表 -->
          <nav aria-label="Page navigation">
            <ul class="pagination">
              <li>
                <a href="#" aria-label="上一页">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
              <li><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li>
                <a href="#" aria-label="下一页">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            </ul>
          </nav>
        </div>
        <!-- //左侧内容区域 -->
      </div>
      <div class="col-md-3">
        <!-- 右侧内容区域 -->
        <div class="main-right">
          <!-- 关注统计 -->
          <div class="follow-stats box-wrap">
            <div>
              <span>关注了</span>
              <strong>12</strong>
            </div>
            <div>
              <span>关注者</span>
              <strong>12</strong>
            </div>
          </div>
          <!-- // 关注统计 -->
          <!-- 右侧页脚 -->
          <div class="right-footer">
            <a href="#">用户指南</a><span class="dot">·</span>
            <a href="#">用户使用协议</a><span class="dot">·</span>
            <a href="#">用户隐私权政策</a>
            <br/>
            <a href="#">侵权举报</a><span class="dot">·</span>
            <a href="#">网上有害信息举报专区</a>
            <br/>
            <a href="#">京ICP证 第10001000号</a>
            <br/>
            <a href="#">京ICP备 第10001000号</a>
            <br/>
            <a href="#">联系我们 &copy; 2020在线问答</a>
          </div>
        <!-- //右侧页脚 -->
        </div>
        <!-- //右侧内容区域 -->
      </div>
    </div>
  </div>

  <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
  <script src="./assets/plugins/jquery-3.4.1.min.js"></script>
  <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
  <script src="./assets/plugins/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>

web_flask/onlineqa/qa_flask/accounts/templates/register.html
{% extends 'base.html' %}
{% from 'macro/form_errors.html' import form_field_errors %}
{% block title %}{{ super() }}-注册{% endblock %}
{% block header %}
  <link rel="stylesheet" href="./assets/style/login.css">
  <link rel="stylesheet" href="//at.alicdn.com/t/font_1658093_nokjvsp8hws.css">
{% endblock %}
{% block layout %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        {# 展示flash消息 #}
        {% include 'components/flash_messages.html' %}
        <div class="login-header">
          <h2 class="title text-center">在线问答系统-注册</h2>
          <div class="slogan text-center">有问题 上问答</div>
        </div>
        <!-- 表单登录 -->
        <form class="login-form box-wrap" method="POST"
              action="{{ url_for('accounts.register') }}">
          {{ form.csrf_token }}
          <div class="form-group">
            <label for="id-user-name">用户名</label>
            {{ form.username }}
          </div>
          {{ form_field_errors(form.username.errors) }}
          <div class="form-group">
            <label for="id-nick-name">昵称</label>
            {{ form.nickname }}
          </div>
          {{ form_field_errors(form.nickname.errors) }}
          <div class="form-group">
            <label for="id-password">密码</label>
            {{ form.password }}
          </div>
          {{ form_field_errors(form.password.errors) }}
          <div class="form-group">
            <label for="id-confirm-password">确认密码</label>
            {{ form.confirm_password }}
          </div>
          {{ form_field_errors(form.confirm_password.errors) }}
          <div class="form-group">
            <button type="submit" class="btn btn-info btn-block btn-lg">注册</button>
          </div>
          <p class="desc">未注册手机验证后自动登录<br/>
            注册即代表同意《用户使用协议》《隐私保护指引》</p>
          <p class="text-right">已有账号，<a href="{{ url_for('accounts.login') }}">点击登录</a></p>
        </form>
        <!-- //表单登录 -->
        <!-- 社交账号登录 -->
        <div class="login-social box-wrap">
          <span>社交账号登录</span>
          <div class="right">
            <span><i class="iconfont icon-wechat"></i>微信</span>
            <span><i class="iconfont icon-qq"></i>QQ</span>
            <span><i class="iconfont icon-weibo"></i>微博</span>
          </div>
        </div>
        <!-- //社交账号登录 -->
        <!-- 页脚 -->
        <div class="login-footer">
          <a href="">关于我们</a>
          <a href="">联系我们</a>
          <a href="">注册机构</a>
          <a href="">专栏</a>
          <br>
          <a href="">京ICP 备1000000012号</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}